### ISSUE TITLE
text shadow on non love songs

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/pop-love-songs#13]
personally i dont think you need the text shadow

<img width="957" alt="image" src="https://github.com/user-attachments/assets/69c18e5b-ce94-4f6d-933d-bc8fdf01a954">

**Comment by davidnmora** [comment]
I'm down, so long as you think it's legible on bubble-view.

<img width="798" alt="image" src="https://github.com/user-attachments/assets/c6d3310d-3272-484f-9dad-2e25362e0ef6">

**Comment by davidnmora** [comment]
I just compromised: super subtle shadow.
<img width="448" alt="image" src="https://github.com/user-attachments/assets/d1486414-957f-49b1-8105-90fa5125d34c">
