### ISSUE TITLE
play button vs. circle

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/pop-love-songs#17]
small observation: the playbutton looks like a bubble, so at first I thought the song's bubble was the play button. one idea is to drop the background circle on the play button and just have the triangle 

<img width="946" alt="image" src="https://github.com/user-attachments/assets/12ff8690-9f62-4b74-9416-37c69e98bf77">

**Comment by davidnmora** [comment]
Good call out! Honestly, I built the thing and I get them confused. I took Jan's suggestion and turned them into squares: 
<img width="371" alt="image" src="https://github.com/user-attachments/assets/986cf7c4-43fe-42a8-8c53-d92eeea52c7a">
