### ISSUE TITLE
x-axis opacity and z-axis

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/pop-love-songs#18]
let's make sure the years are always on the top of the chart and are all full-opacity so that they're super legible 

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/f586f8f0-fa42-4aa8-965d-b3c46cc9136b">

**Comment by davidnmora** [comment]
Good call, I also added a subtle background-matching text-shadow, to help.
