### ISSUE TITLE
"tap to continue" has overlap with boomer bob

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/pop-love-songs#21]
<img width="833" alt="image" src="https://github.com/user-attachments/assets/64089612-f8b3-47a8-8f29-7fad0123ca87">

consider putting in the bottom left corner

**Comment by davidnmora** [comment]
Applied a general fix:
- text is slightly smaller on mobile
- text is z-indexed above the image, and has text-shadow, so even in the rare phone size that it slightly overlaps, it's very readable
