### ISSUE TITLE
extra text shadow

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/pop-love-songs#25]
<img width="200" alt="image" src="https://github.com/user-attachments/assets/6af7f7e3-c47f-43f0-b747-dee64797a231">

there is some text shadow on the bold span here, which you can probably remove with:
<img width="159" alt="image" src="https://github.com/user-attachments/assets/ee7f5075-ce11-4024-94bc-c44ace47e57e">

**Comment by davidnmora** [comment]
Wow, ok, I never would have guessed setting position relative would somehow cause a re-paint in a way that fixes this. Thank you! (I'm gonna keep this nugget with me going forward)

I was struggling with this same issue with other in-text spans. Fixed it for them all!
